version: '3.8'
services:
  catalog:
    image: catalog:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/catalog
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - books:/app/data

  order:
    image: order:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      CATALOG_SERVICE_URL: http://catalog:8080

  postgres-service:
    image: postgres:17-bookworm
    container_name: postgres-service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog
    volumes:
      - books:/var/lib/postgresql/data
volumes:
  books: