create table books (
                       title VARCHAR(255),
                       author VARCHAR(255),
                       isbn VARCHAR(255),
                       pages INT,
                       genre VARCHAR(255),
                       description VARCHAR(MAX),
	price DECIMAL(5,2)
);
insert into books (title, author, isbn, pages, genre, description, price) values ('Cerulean Serenity', 'Joshua Martinez', '784827138-2', 938, 'FANTASY', 'Modern rustic with a blend of natural and industrial elements', 74.95);
insert into books (title, author, isbn, pages, genre, description, price) values ('Guava Glow', 'Michelle Carter', '949300256-X', 726, 'TEXTBOOK', 'Nautical beach house with a coastal and maritime theme', 77.45);
insert into books (title, author, isbn, pages, genre, description, price) values ('Hazelnut Haze', 'Randy Peterson', '259948000-0', 254, 'NOVAL', 'Asian zen retreat with a serene and tranquil ambiance', 59.86);
insert into books (title, author, isbn, pages, genre, description, price) values ('Marigold Meadows', 'Ashley Perez', '064228017-7', 656, 'TEXTBOOK', 'Retro mod style with bold colors and geometric patterns', 79.22);
insert into books (title, author, isbn, pages, genre, description, price) values ('Cherry Blossom Ballet', 'Eric Hernandez', '559019426-1', 530, 'TEXTBOOK', 'Gothic chic with dark colors and dramatic accents', 89.96);
insert into books (title, author, isbn, pages, genre, description, price) values ('Plumeria Paradise', 'Cameron Reed', '883218844-9', 615, 'CRIME', 'Asian zen retreat with a serene and tranquil ambiance', 65.69);
insert into books (title, author, isbn, pages, genre, description, price) values ('Cotton Candy Clouds', 'Dustin Brooks', '023343173-X', 558, 'ROMANCE', 'Contemporary design with clean lines and modern finishes', 47.44);
insert into books (title, author, isbn, pages, genre, description, price) values ('Lemon Lullaby', 'Katherine Ward', '665749192-1', 556, 'FANTASY', 'Glamorous Hollywood regency with luxe finishes and elegant touches', 45.19);
insert into books (title, author, isbn, pages, genre, description, price) values ('Minty Magic', 'Regina Sullivan', '881368565-3', 869, 'GUIDE', 'Luxurious and opulent with high-end finishes', 96.93);
insert into books (title, author, isbn, pages, genre, description, price) values ('Mocha Madness', 'Ethan Peterson', '929744599-3', 921, 'TEXTBOOK', 'Scandinavian hygge style with a focus on coziness and comfort', 76.14);
insert into books (title, author, isbn, pages, genre, description, price) values ('Turquoise Tranquility', 'Rachel Adams', '703896182-9', 906, 'ROMANCE', 'Mid-century bohemian with a mix of retro and eclectic decor', 27.7);
insert into books (title, author, isbn, pages, genre, description, price) values ('Emerald Isle', 'Austin Kelly', '318582652-3', 492, 'TEXTBOOK', 'Artistic loft space with a creative and inspiring atmosphere', 62.0);
insert into books (title, author, isbn, pages, genre, description, price) values ('Papaya Perfection', 'Heather Ortiz', '677676205-8', 647, 'THRILLER', 'Retro mod style with bold colors and geometric patterns', 94.57);
insert into books (title, author, isbn, pages, genre, description, price) values ('Violet Veil', 'Austin Kelly', '462212733-4', 204, 'HORROR', 'Mid-century bohemian with a mix of retro and eclectic decor', 26.84);
insert into books (title, author, isbn, pages, genre, description, price) values ('Amber Waves', 'Jared Hughes', '912617941-5', 845, 'GUIDE', 'Vintage boho with a mix of vintage and bohemian decor', 30.75);
insert into books (title, author, isbn, pages, genre, description, price) values ('The Secret Garden', 'Ashley Perez', '103347100-3', 580, 'FANTASY', 'Scandinavian simplicity with a focus on comfort and coziness', 24.76);
insert into books (title, author, isbn, pages, genre, description, price) values ('Indigo Infinity', 'Andrew Wright', '631494138-5', 693, 'CRIME', 'Moroccan-inspired oasis with vibrant colors and intricate details', 75.98);
insert into books (title, author, isbn, pages, genre, description, price) values ('Ebony Echo', 'Angela Rivera', '157029947-1', 89, 'TEXTBOOK', 'Bright and airy with plenty of natural light', 56.12);
insert into books (title, author, isbn, pages, genre, description, price) values ('Whispers in the Wind', 'Gavin Wright', '007882863-5', 747, 'HORROR', 'Art deco glamour with a touch of old Hollywood regency', 83.39);
insert into books (title, author, isbn, pages, genre, description, price) values ('Butterscotch Bliss', 'Ryan Foster', '997093022-2', 458, 'SCIFI', 'Quaint and charming cottage with a peaceful atmosphere', 24.42);
insert into books (title, author, isbn, pages, genre, description, price) values ('Crimson Horizon', 'Cassandra Morris', '397630950-8', 82, 'HORROR', 'Farmhouse chic with a blend of rustic and modern elements', 37.5);
insert into books (title, author, isbn, pages, genre, description, price) values ('Starfruit Symphony', 'Peter Foster', '323342567-8', 519, 'CRIME', 'Modern rustic with a blend of natural and industrial elements', 44.18);
insert into books (title, author, isbn, pages, genre, description, price) values ('Plumeria Paradise', 'Veronica Young', '212726439-8', 661, 'SCIFI', 'Rustic lodge feel with woodsy accents and cozy furnishings', 61.96);
insert into books (title, author, isbn, pages, genre, description, price) values ('Midnight Moon', 'Ethan Peterson', '941713046-3', 594, 'CRIME', 'Asian zen retreat with a serene and tranquil ambiance', 91.61);
insert into books (title, author, isbn, pages, genre, description, price) values ('Bronze Breeze', 'Michelle Carter', '698931825-2', 121, 'CRIME', 'Boho eclectic with a mix of global influences and bohemian flair', 41.05);
insert into books (title, author, isbn, pages, genre, description, price) values ('Pewter Peaks', 'Lauren White', '990377089-8', 689, 'ROMANCE', 'Boho eclectic with a mix of global influences and bohemian flair', 28.97);
insert into books (title, author, isbn, pages, genre, description, price) values ('Mauve Mist', 'Veronica Young', '408435508-9', 485, 'BIOGRAPHY', 'Farmhouse chic with a blend of rustic and modern elements', 91.31);
insert into books (title, author, isbn, pages, genre, description, price) values ('Pearl Paradise', 'Regina Sullivan', '782521550-8', 613, 'TEXTBOOK', 'Art deco glamour with a touch of old Hollywood regency', 57.37);
insert into books (title, author, isbn, pages, genre, description, price) values ('Peachy Perfection', 'Matthew Lopez', '923254417-2', 572, 'CRIME', 'Modern rustic with a blend of natural and industrial elements', 84.41);
insert into books (title, author, isbn, pages, genre, description, price) values ('Scarlet Sunset', 'John Smith', '586234530-2', 74, 'HORROR', 'Bohemian flair with eclectic decor and vibrant colors', 82.78);
insert into books (title, author, isbn, pages, genre, description, price) values ('Gingerbread Glade', 'Lucas Murphy', '618744514-7', 228, 'CRIME', 'Moroccan-inspired oasis with vibrant colors and intricate details', 41.21);
insert into books (title, author, isbn, pages, genre, description, price) values ('Pearl Paradise', 'Desiree Fisher', '668367372-1', 472, 'TEXTBOOK', 'Rustic lodge feel with woodsy accents and cozy furnishings', 64.05);
insert into books (title, author, isbn, pages, genre, description, price) values ('The Secret Garden', 'Dustin Brooks', '846517749-X', 693, 'FANTASY', 'Farmhouse chic with a blend of rustic and modern elements', 63.38);
insert into books (title, author, isbn, pages, genre, description, price) values ('Golden Sands', 'Olivia Garcia', '649617646-9', 604, 'SCIFI', 'Cozy cottage with shabby chic decor and vintage finds', 84.06);
insert into books (title, author, isbn, pages, genre, description, price) values ('Aqua Adventure', 'Dustin Brooks', '236493856-2', 929, 'HORROR', 'Modern and stylish with a touch of vintage charm', 49.05);
insert into books (title, author, isbn, pages, genre, description, price) values ('Sapphire Skies', 'Kevin Davis', '557006185-1', 969, 'ROMANCE', 'Elegant and sophisticated with a classic touch', 43.49);
insert into books (title, author, isbn, pages, genre, description, price) values ('Azure Dreams', 'Madison Barnes', '445611922-5', 727, 'THRILLER', 'Contemporary urban with clean lines and modern finishes', 34.65);
insert into books (title, author, isbn, pages, genre, description, price) values ('Crimson Horizon', 'Matthew Lopez', '933564428-5', 485, 'FANTASY', 'Asian-inspired decor with a zen and tranquil ambiance', 50.46);
insert into books (title, author, isbn, pages, genre, description, price) values ('Gingerbread Glade', 'Samantha Clark', '792119126-6', 936, 'FANTASY', 'Industrial chic with exposed brick and metal accents', 51.28);
insert into books (title, author, isbn, pages, genre, description, price) values ('Emerald Isle', 'Daniel Lewis', '321038013-9', 288, 'CRIME', 'Asian zen retreat with a serene and tranquil ambiance', 81.45);
insert into books (title, author, isbn, pages, genre, description, price) values ('Lotus Lagoon', 'Philip Kelly', '787899151-0', 443, 'GUIDE', 'Asian zen retreat with a serene and tranquil ambiance', 23.92);
insert into books (title, author, isbn, pages, genre, description, price) values ('Mulberry Moon', 'Dustin Brooks', '825090723-X', 277, 'SCIFI', 'Southwestern desert vibe with warm earth tones and natural textures', 38.38);
insert into books (title, author, isbn, pages, genre, description, price) values ('Coral Cove', 'Jordan Torres', '846939305-7', 388, 'HORROR', 'French country style with a rustic and romantic feel', 93.39);
insert into books (title, author, isbn, pages, genre, description, price) values ('Ivory Illusion', 'Travis Patel', '066049930-4', 117, 'ROMANCE', 'Modern and stylish with a touch of vintage charm', 74.68);
insert into books (title, author, isbn, pages, genre, description, price) values ('Caramel Cascade', 'Evan Wright', '953810750-0', 502, 'HORROR', 'Nautical beach house with a coastal and maritime theme', 98.4);
insert into books (title, author, isbn, pages, genre, description, price) values ('Jade Jungle', 'Julia Martinez', '552868742-X', 238, 'FANTASY', 'Modern rustic with a blend of natural and industrial elements', 20.94);
insert into books (title, author, isbn, pages, genre, description, price) values ('Mystic Dreams', 'Sarah Wilson', '194239374-1', 893, 'GUIDE', 'Bright and airy with plenty of natural light', 23.67);
insert into books (title, author, isbn, pages, genre, description, price) values ('Magenta Mirage', 'David Lee', '448710587-0', 298, 'TEXTBOOK', 'Rustic lodge feel with woodsy accents and cozy furnishings', 24.87);
insert into books (title, author, isbn, pages, genre, description, price) values ('Ebony Echo', 'Brian Rodriguez', '212039383-4', 529, 'THRILLER', 'Art deco glamour with a touch of old Hollywood regency', 75.54);
insert into books (title, author, isbn, pages, genre, description, price) values ('Caramel Cascade', 'John Smith', '323219416-8', 831, 'NOVAL', 'Traditional elegance with classic furnishings and timeless appeal', 89.04);
insert into books (title, author, isbn, pages, genre, description, price) values ('Dancing Shadows', 'Justin Rivera', '461206215-9', 180, 'HORROR', 'Farmhouse chic with a blend of rustic and modern elements', 38.44);
insert into books (title, author, isbn, pages, genre, description, price) values ('Lavender Lagoon', 'Christina Price', '998799650-7', 874, 'THRILLER', 'Asian-inspired decor with a zen and tranquil ambiance', 51.95);
insert into books (title, author, isbn, pages, genre, description, price) values ('Dancing Shadows', 'Wesley Reed', '471047491-5', 110, 'TEXTBOOK', 'French provincial charm with elegant furnishings and decor', 88.86);
insert into books (title, author, isbn, pages, genre, description, price) values ('Golden Sands', 'Kevin Davis', '917981171-X', 687, 'ROMANCE', 'Vintage boho with a mix of vintage and bohemian decor', 90.44);
insert into books (title, author, isbn, pages, genre, description, price) values ('Kumquat Kaleidoscope', 'Oscar Ward', '887409461-2', 793, 'FANTASY', 'Boho eclectic with a mix of global influences and bohemian flair', 29.36);
insert into books (title, author, isbn, pages, genre, description, price) values ('Peachy Perfection', 'Brent Thompson', '558717826-9', 603, 'CRIME', 'Farmhouse chic with a blend of rustic and modern elements', 97.44);
insert into books (title, author, isbn, pages, genre, description, price) values ('Whispers in the Wind', 'Derek Ross', '177100911-X', 480, 'GUIDE', 'Art deco glamour with a touch of old Hollywood regency', 61.43);
insert into books (title, author, isbn, pages, genre, description, price) values ('Orchid Oasis', 'Gavin Wright', '567107796-6', 671, 'BIOGRAPHY', 'Asian-inspired decor with a zen and tranquil ambiance', 71.79);
insert into books (title, author, isbn, pages, genre, description, price) values ('Magenta Mirage', 'Michelle Carter', '235301707-X', 854, 'CRIME', 'Scandinavian hygge style with a focus on coziness and comfort', 38.07);
insert into books (title, author, isbn, pages, genre, description, price) values ('Cerulean Serenity', 'Daniel Lewis', '357766951-9', 641, 'BIOGRAPHY', 'Rustic cabin feel with woodsy accents and cozy furnishings', 70.96);
insert into books (title, author, isbn, pages, genre, description, price) values ('Teal Tempest', 'Troy Patel', '769824583-7', 58, 'NOVAL', 'Art deco glamour with a touch of old Hollywood', 39.99);
insert into books (title, author, isbn, pages, genre, description, price) values ('Jade Jungle', 'John Smith', '437540413-2', 156, 'THRILLER', 'Mid-century bohemian with a mix of retro and eclectic decor', 70.47);
insert into books (title, author, isbn, pages, genre, description, price) values ('The Secret Garden', 'Courtney Reed', '111131499-3', 724, 'THRILLER', 'Moroccan-inspired oasis with vibrant colors and intricate details', 62.12);
insert into books (title, author, isbn, pages, genre, description, price) values ('Jasmine Jubilee', 'Samantha Clark', '494319866-X', 359, 'TEXTBOOK', 'Industrial chic with exposed brick and metal accents', 60.28);
insert into books (title, author, isbn, pages, genre, description, price) values ('Cotton Candy Clouds', 'Jared Hughes', '364888377-1', 720, 'BIOGRAPHY', 'Art deco glamour with a touch of old Hollywood regency', 39.02);
insert into books (title, author, isbn, pages, genre, description, price) values ('Pewter Peaks', 'Kelsey Turner', '778353870-3', 876, 'ROMANCE', 'Boho-chic with a mix of patterns', 90.89);
insert into books (title, author, isbn, pages, genre, description, price) values ('Blackberry Bliss', 'Brent Thompson', '992299760-6', 720, 'HORROR', 'Minimalist design with a focus on simplicity and functionality', 40.78);
insert into books (title, author, isbn, pages, genre, description, price) values ('Kumquat Kaleidoscope', 'Ethan Peterson', '994401975-5', 998, 'ROMANCE', 'Scandinavian simplicity with a focus on comfort and coziness', 37.0);
insert into books (title, author, isbn, pages, genre, description, price) values ('Starfruit Symphony', 'Justin Rivera', '120308248-7', 549, 'THRILLER', 'Farmhouse chic with a blend of rustic and modern elements', 66.81);
insert into books (title, author, isbn, pages, genre, description, price) values ('Coral Cove', 'Veronica Young', '108155803-2', 453, 'SCIFI', 'Tropical oasis with lush greenery and exotic accents', 38.79);
insert into books (title, author, isbn, pages, genre, description, price) values ('Plumeria Paradise', 'Jessica Martinez', '591491964-9', 243, 'ROMANCE', 'Farmhouse chic with a blend of rustic and modern elements', 52.68);
insert into books (title, author, isbn, pages, genre, description, price) values ('Mulberry Moon', 'Justin Rivera', '525899687-5', 977, 'SCIFI', 'Glamorous Hollywood regency style with luxe finishes', 29.14);
insert into books (title, author, isbn, pages, genre, description, price) values ('Echoes of Eternity', 'Regina Sullivan', '347095056-3', 122, 'BIOGRAPHY', 'Tropical paradise with lush greenery and vibrant colors', 91.97);
insert into books (title, author, isbn, pages, genre, description, price) values ('Gingerbread Glade', 'Tyler Ward', '916632571-4', 219, 'NOVAL', 'Rustic lodge feel with woodsy accents and cozy furnishings', 76.07);
insert into books (title, author, isbn, pages, genre, description, price) values ('Mocha Madness', 'Vanessa Sanchez', '736901640-4', 879, 'ROMANCE', 'Art deco glamour with a touch of old Hollywood regency', 54.24);
insert into books (title, author, isbn, pages, genre, description, price) values ('Peachy Perfection', 'Alexis Ramirez', '787656889-0', 535, 'TEXTBOOK', 'Farmhouse chic with a blend of rustic and modern elements', 63.74);
insert into books (title, author, isbn, pages, genre, description, price) values ('Magenta Mirage', 'Derek Ross', '492923355-0', 200, 'HORROR', 'French country style with a rustic and romantic feel', 61.45);
insert into books (title, author, isbn, pages, genre, description, price) values ('Olive Oasis', 'Jason Martinez', '867605407-X', 193, 'CRIME', 'Mid-century bohemian with a mix of retro and eclectic decor', 74.24);
insert into books (title, author, isbn, pages, genre, description, price) values ('Butterscotch Bliss', 'Savannah Barnes', '010787999-9', 421, 'THRILLER', 'Traditional elegance with classic furnishings and timeless appeal', 83.95);
insert into books (title, author, isbn, pages, genre, description, price) values ('Amber Waves', 'Nathan Coleman', '428962680-7', 857, 'NOVAL', 'Asian zen retreat with a serene and tranquil ambiance', 77.6);
insert into books (title, author, isbn, pages, genre, description, price) values ('Pineapple Paradise', 'Miranda Turner', '622148169-4', 595, 'TEXTBOOK', 'Cozy cottage feel with shabby chic decor and vintage finds', 27.05);
insert into books (title, author, isbn, pages, genre, description, price) values ('Cinnamon Swirl', 'Alexis Ramirez', '365277521-X', 517, 'TEXTBOOK', 'Artistic loft space with a creative and inspiring atmosphere', 26.33);
insert into books (title, author, isbn, pages, genre, description, price) values ('Copper Canyon', 'Madison Barnes', '387341052-4', 623, 'NOVAL', 'Glamorous and chic with a touch of Hollywood regency', 40.57);
insert into books (title, author, isbn, pages, genre, description, price) values ('Olive Oasis', 'Eric Hernandez', '178472895-0', 333, 'TEXTBOOK', 'Rustic lodge feel with woodsy accents and cozy furnishings', 68.74);
insert into books (title, author, isbn, pages, genre, description, price) values ('Ruby Rain', 'Travis Patel', '672039195-X', 189, 'TEXTBOOK', 'Moroccan-inspired oasis with vibrant colors and intricate details', 24.27);
insert into books (title, author, isbn, pages, genre, description, price) values ('Starfruit Symphony', 'Paige Sanchez', '642366602-4', 664, 'CRIME', 'Gothic chic with dark colors and dramatic accents', 60.31);
insert into books (title, author, isbn, pages, genre, description, price) values ('Moonlit Melody', 'Lauren White', '119038328-4', 469, 'BIOGRAPHY', 'Farmhouse style with a cozy and rustic feel', 43.63);
insert into books (title, author, isbn, pages, genre, description, price) values ('Dragonfruit Dream', 'Lillian Coleman', '925461795-4', 821, 'BIOGRAPHY', 'Boho eclectic with a mix of global influences and bohemian flair', 36.58);
insert into books (title, author, isbn, pages, genre, description, price) values ('Jasmine Jubilee', 'John Smith', '410093372-X', 495, 'ROMANCE', 'Mid-century modern with clean lines and retro charm', 37.14);
insert into books (title, author, isbn, pages, genre, description, price) values ('Coral Cove', 'Matthew Lopez', '629152567-4', 313, 'GUIDE', 'Whimsical wonderland with bright colors and playful decor', 42.71);
insert into books (title, author, isbn, pages, genre, description, price) values ('Saffron Sunset', 'John Smith', '547304473-5', 757, 'NOVAL', 'Boho-chic with a mix of patterns', 73.34);
insert into books (title, author, isbn, pages, genre, description, price) values ('Whispering Pines', 'Regina Sullivan', '160869284-1', 941, 'TEXTBOOK', 'Tropical paradise with lush greenery and vibrant colors', 30.46);
insert into books (title, author, isbn, pages, genre, description, price) values ('Violet Veil', 'Philip Kelly', '789273394-9', 401, 'NOVAL', 'Vintage industrial with a mix of vintage and industrial elements', 45.84);
insert into books (title, author, isbn, pages, genre, description, price) values ('Echoes of Eternity', 'Vanessa Sanchez', '971312287-9', 266, 'CRIME', 'French provincial charm with elegant furnishings and decor', 70.2);
insert into books (title, author, isbn, pages, genre, description, price) values ('Licorice Lullaby', 'Melissa Hall', '626368081-4', 136, 'SCIFI', 'Southwestern desert vibe with warm earth tones and natural textures', 99.99);
insert into books (title, author, isbn, pages, genre, description, price) values ('Cinnamon Swirl', 'John Smith', '362731274-0', 925, 'SCIFI', 'Scandinavian simplicity with a focus on comfort and coziness', 57.18);
insert into books (title, author, isbn, pages, genre, description, price) values ('Magnolia Melody', 'Veronica Young', '628096364-0', 592, 'HORROR', 'Tropical oasis with lush greenery and exotic accents', 55.81);
insert into books (title, author, isbn, pages, genre, description, price) values ('Golden Sands', 'David Lee', '652699479-2', 839, 'THRILLER', 'Modern rustic with a blend of natural and industrial elements', 57.49);
insert into books (title, author, isbn, pages, genre, description, price) values ('Bronze Breeze', 'Derek Ross', '166090686-5', 199, 'SCIFI', 'Modern rustic with a blend of natural and industrial elements', 76.53);
insert into books (title, author, isbn, pages, genre, description, price) values ('Sunflower Serenade', 'Matthew Lopez', '386013770-0', 604, 'TEXTBOOK', 'Art deco glamour with a touch of old Hollywood regency', 50.25);
insert into books (title, author, isbn, pages, genre, description, price) values ('Java Programming 101', 'Emily Brown', '415621811-2', 351, 'TEXTBOOK', 'Java Programming Cookbook', 52.1);
insert into books (title, author, isbn, pages, genre, description, price) values ('Java Programming 101', 'Michael Lee', '097881349-9', 254, 'TEXTBOOK', 'Mastering Java Development', 29.71);
insert into books (title, author, isbn, pages, genre, description, price) values ('Java Programming 101', 'Emily Brown', '934820549-8', 396, 'GUIDE', 'Advanced Java Concepts', 25.15);
insert into books (title, author, isbn, pages, genre, description, price) values ('Java for Beginners', 'Alex Johnson', '995026223-2', 90, 'TEXTBOOK', 'Advanced Java Concepts', 38.83);
insert into books (title, author, isbn, pages, genre, description, price) values ('Mastering Java', 'Jane Smith', '344406553-1', 350, 'TEXTBOOK', 'Advanced Java Concepts', 28.91);
insert into books (title, author, isbn, pages, genre, description, price) values ('Java in Practice', 'Michael Lee', '861211025-4', 225, 'TEXTBOOK', 'Java for Beginners', 146.55);
insert into books (title, author, isbn, pages, genre, description, price) values ('Mastering Java', 'Emily Brown', '081965056-0', 227, 'GUIDE', 'Advanced Java Concepts', 138.9);
